// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HttpService handles all HTTP request execution from the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * FormatJSON takes a JSON string and returns it pretty-printed.
 */
export function FormatJSON(input: string): $CancellablePromise<string> {
    return $Call.ByID(3506754260, input);
}

/**
 * SendRequest executes an HTTP request and returns the response with timing details.
 */
export function SendRequest(payload: $models.RequestPayload): $CancellablePromise<$models.ResponsePayload> {
    return $Call.ByID(4118071912, payload);
}
