// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * KeyValue represents a key-value pair for headers, params, form data.
 */
export interface KeyValue {
    "key": string;
    "value": string;
    "enabled": boolean;
}

/**
 * RequestPayload is the request configuration sent from the frontend.
 */
export interface RequestPayload {
    "method": string;
    "url": string;
    "headers": KeyValue[] | null;
    "queryParams": KeyValue[] | null;

    /**
     * none, json, text, form-urlencoded, form-data, binary
     */
    "bodyType": string;
    "body": string;
    "formData": KeyValue[] | null;

    /**
     * seconds, 0 = no timeout
     */
    "timeout": number;
    "followRedirects": boolean;
    "verifySSL": boolean;
}

/**
 * ResponsePayload is the response data sent back to the frontend.
 */
export interface ResponsePayload {
    "status": number;
    "statusText": string;
    "headers": { [_ in string]?: string } | null;
    "body": string;
    "size": number;

    /**
     * milliseconds
     */
    "duration": number;
    "dnsTime": number;
    "connectTime": number;
    "tlsTime": number;

    /**
     * time to first byte
     */
    "ttfbTime": number;
    "error"?: string;
    "protocol": string;
    "remoteAddr": string;
    "contentType": string;
    "redirectCount": number;
}
