// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CollectionService manages workspaces, folders, requests, and responses (CRUD + persistence).
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ClearResponseHistory(requestID: string): $CancellablePromise<void> {
    return $Call.ByID(1962548055, requestID);
}

export function CreateFolder(workspaceID: string, name: string, parentID: string): $CancellablePromise<$models.Folder> {
    return $Call.ByID(675438893, workspaceID, name, parentID);
}

export function CreateWorkspace(name: string): $CancellablePromise<$models.Workspace> {
    return $Call.ByID(3409368390, name);
}

export function DeleteEnvironment(id: string): $CancellablePromise<void> {
    return $Call.ByID(2326062127, id);
}

export function DeleteFolder(id: string): $CancellablePromise<void> {
    return $Call.ByID(4290408346, id);
}

export function DeleteRequest(id: string): $CancellablePromise<void> {
    return $Call.ByID(2058166239, id);
}

export function DuplicateRequest(id: string): $CancellablePromise<$models.SavedRequest> {
    return $Call.ByID(1982219123, id);
}

export function ListEnvironments(workspaceID: string): $CancellablePromise<$models.Environment[] | null> {
    return $Call.ByID(1004451175, workspaceID);
}

export function ListFolders(workspaceID: string): $CancellablePromise<$models.Folder[] | null> {
    return $Call.ByID(239790014, workspaceID);
}

export function ListRequests(workspaceID: string): $CancellablePromise<$models.SavedRequest[] | null> {
    return $Call.ByID(3906760535, workspaceID);
}

export function ListResponses(requestID: string, limit: number): $CancellablePromise<$models.SavedResponse[] | null> {
    return $Call.ByID(1244794499, requestID, limit);
}

export function ListWorkspaces(): $CancellablePromise<$models.Workspace[] | null> {
    return $Call.ByID(1453798971);
}

export function SaveEnvironment(env: $models.Environment): $CancellablePromise<$models.Environment> {
    return $Call.ByID(161837201, env);
}

export function SaveRequest(req: $models.SavedRequest): $CancellablePromise<$models.SavedRequest> {
    return $Call.ByID(539801345, req);
}

export function SaveResponse(requestID: string, resp: $models.SavedResponse): $CancellablePromise<$models.SavedResponse> {
    return $Call.ByID(880502655, requestID, resp);
}

export function SetActiveEnvironment(workspaceID: string, envID: string): $CancellablePromise<void> {
    return $Call.ByID(1810698266, workspaceID, envID);
}
