// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GraphQLService handles GraphQL introspection and query execution.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ExecuteQuery sends a GraphQL query/mutation.
 */
export function ExecuteQuery(req: $models.GraphQLRequest): $CancellablePromise<$models.GraphQLResponse> {
    return $Call.ByID(3870997841, req);
}

/**
 * IntrospectSchema fetches the GraphQL schema via introspection query.
 */
export function IntrospectSchema(url: string, headers: $models.Pair[] | null): $CancellablePromise<$models.GraphQLSchema> {
    return $Call.ByID(969318912, url, headers);
}
