// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * GrpcService handles gRPC requests.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * ParseProtoFile parses .proto file(s) and returns services/methods with input templates.
 */
export function ParseProtoFile(filePath: string, importPaths: string[] | null): $CancellablePromise<$models.GrpcServiceInfo[] | null> {
    return $Call.ByID(1143055020, filePath, importPaths);
}

/**
 * SendUnary sends a unary gRPC request using a proto file for type information.
 */
export function SendUnary(address: string, protoFile: string, importPaths: string[] | null, fullMethod: string, messageJSON: string, metadataPairs: $models.Pair[] | null): $CancellablePromise<$models.GrpcResponse> {
    return $Call.ByID(2218822166, address, protoFile, importPaths, fullMethod, messageJSON, metadataPairs);
}
