// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * HttpService handles all HTTP request execution from the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelRequest explicitly aborts a native request. This works independently
 * of the frontend bridge promise and is reliable during DNS/TLS/body reads.
 */
export function CancelRequest(requestID: string): $CancellablePromise<boolean> {
    return $Call.ByID(977365476, requestID);
}

/**
 * FormatJSON takes a JSON string and returns it pretty-printed.
 */
export function FormatJSON(input: string): $CancellablePromise<string> {
    return $Call.ByID(306976396, input);
}

/**
 * SendRequest executes an HTTP request and returns the response with timing details.
 * The context is provided by Wails and cancelled when the frontend calls .cancel() on the promise.
 */
export function SendRequest(payload: $models.RequestPayload): $CancellablePromise<$models.ResponsePayload> {
    return $Call.ByID(477429584, payload);
}
