// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as json$0 from "../../encoding/json/models.js";

export interface AuthConfig {
    "type": string;
    "basic"?: json$0.RawMessage;
    "bearer"?: json$0.RawMessage;
    "apiKey"?: json$0.RawMessage;
}

export interface EnvVariable {
    "name": string;
    "value": string;
    "enabled": boolean;
}

export interface Environment {
    "id": string;
    "workspaceId": string;
    "name": string;
    "variables": EnvVariable[] | null;
    "isActive": boolean;
    "createdAt": number;
    "updatedAt": number;
}

export interface Folder {
    "id": string;
    "workspaceId": string;
    "parentId"?: string;
    "name": string;
    "sortOrder": number;
    "createdAt": number;
    "updatedAt": number;
}

export interface GraphQLArgument {
    "name": string;
    "type": string;
    "defaultValue"?: string;
}

export interface GraphQLField {
    "name": string;
    "description"?: string;
    "type": string;
    "args"?: GraphQLArgument[] | null;
}

export interface GraphQLRequest {
    "url": string;
    "query": string;
    "variables": string;
    "headers": Pair[] | null;
}

export interface GraphQLResponse {
    "data": string;
    "errors"?: string;
    "duration": number;
    "error"?: string;
}

export interface GraphQLSchema {
    "types": GraphQLType[] | null;
    "queries": GraphQLField[] | null;
    "mutations": GraphQLField[] | null;
}

export interface GraphQLType {
    "name": string;
    "kind": string;
    "fields"?: GraphQLField[] | null;
}

export interface GrpcMethod {
    "name": string;
    "fullName": string;
    "inputType": string;
    "outputType": string;
    "isClientStream": boolean;
    "isServerStream": boolean;
    "inputTemplate": string;
}

export interface GrpcResponse {
    "data": string;
    "metadata": { [_ in string]?: string } | null;
    "duration": number;
    "error"?: string;
}

export interface GrpcServiceInfo {
    "name": string;
    "methods": GrpcMethod[] | null;
}

/**
 * KeyValue represents a key-value pair for headers, params, form data.
 */
export interface KeyValue {
    "key": string;
    "value": string;
    "enabled": boolean;
    "valueType"?: string;
    "fileName"?: string;
}

export interface Pair {
    "id": string;
    "name": string;
    "value": string;
    "enabled": boolean;
}

/**
 * RequestPayload is the request configuration sent from the frontend.
 */
export interface RequestPayload {
    "requestId": string;
    "method": string;
    "url": string;
    "headers": KeyValue[] | null;
    "queryParams": KeyValue[] | null;

    /**
     * none, json, text, form-urlencoded, form-data, binary
     */
    "bodyType": string;
    "body": string;
    "formData": KeyValue[] | null;

    /**
     * seconds, 0 = no timeout
     */
    "timeout": number;
    "followRedirects": boolean;
    "verifySSL": boolean;
    "maxRedirects": number;
}

export interface RequestSettings {
    "timeout": number;
    "followRedirects": boolean;
    "verifySSL": boolean;
    "maxRedirects": number;
}

/**
 * ResponsePayload is the response data sent back to the frontend.
 */
export interface ResponsePayload {
    "status": number;
    "statusText": string;
    "headers": { [_ in string]?: string } | null;
    "body": string;
    "size": number;

    /**
     * milliseconds (fractional for sub-ms)
     */
    "duration": number;
    "dnsTime": number;
    "connectTime": number;
    "tlsTime": number;

    /**
     * time to first byte
     */
    "ttfbTime": number;
    "error"?: string;
    "protocol": string;
    "remoteAddr": string;
    "contentType": string;
    "redirectCount": number;
}

export interface SavedRequest {
    "id": string;
    "workspaceId": string;
    "folderId"?: string;
    "name": string;
    "method": string;
    "url": string;
    "headers": Pair[] | null;
    "urlParameters": Pair[] | null;
    "bodyType": string;
    "body": string;
    "formData": Pair[] | null;
    "auth": AuthConfig;
    "settings": RequestSettings;
    "description": string;
    "preRequestScript"?: string;
    "postResponseScript"?: string;
    "sortOrder": number;
    "createdAt": number;
    "updatedAt": number;
}

export interface SavedResponse {
    "id": string;
    "requestId": string;
    "status": number;
    "statusText": string;
    "headers": string;
    "body": string;
    "size": number;
    "duration": number;
    "dnsTime": number;
    "connectTime": number;
    "tlsTime": number;
    "ttfbTime": number;
    "error": string;
    "protocol": string;
    "remoteAddr": string;
    "contentType": string;
    "redirectCount": number;
    "createdAt": number;
}

export interface Workspace {
    "id": string;
    "name": string;
    "createdAt": number;
    "updatedAt": number;
}
