// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * WebSocketService manages live WebSocket connections. Each connection runs a
 * read goroutine that streams inbound frames to the frontend via the single
 * "ws:event" application event, keyed by a caller-supplied connID.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Close ends the connection with a normal-closure handshake.
 */
export function Close(connID: string): $CancellablePromise<void> {
    return $Call.ByID(4140091890, connID);
}

/**
 * Connect dials the WebSocket at url and begins streaming inbound frames. Any
 * existing connection under the same connID is closed first. Optional
 * subprotocols are comma-separated.
 */
export function Connect(connID: string, url: string, headers: $models.Pair[] | null, subprotocols: string): $CancellablePromise<void> {
    return $Call.ByID(3590315908, connID, url, headers, subprotocols);
}

/**
 * Send writes a UTF-8 text frame to the connection.
 */
export function Send(connID: string, message: string): $CancellablePromise<void> {
    return $Call.ByID(2908183628, connID, message);
}
